CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 1 pretraining.py \
    --model_name_or_path yidongdata/model/google/gemma-3-4b-it \
    --train_file_dir yidongdata/data/tlpttraindir \
    --validation_file_dir yidongdata/data/pttlvaldir \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --use_peft True \
    --seed 42 \
    --max_train_samples -1 \
    --max_eval_samples -1 \
    --num_train_epochs 1 \
    --learning_rate 2e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --eval_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 13 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 64 \
    --block_size 512 \
    --group_by_length True \
    --output_dir yidongdata/gemmatlpretrain \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype bfloat16 \
    --bf16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --cache_dir ./cache
